version: "3.3"
services:
  tor:
    image: localhost/tor-hidden-service:v0.4.4.6
    restart: always
    environment:
      HTTPD_TOR_SERVICE_HOSTS: 80:httpd:8080
      HTTPD_TOR_SERVICE_VERSION: 3
      TOR_EXTRA_OPTIONS: |
        DataDirectory /var/lib/tor/hidden_service
        ControlPort 0.0.0.0:9051
        CookieAuthentication 1
    volumes:
      - tor_volume:/var/lib/tor/hidden_service/
    depends_on:
      - httpd

  vanguards:
    image: localhost/vanguards:latest
    restart: always
    environment:
      GLOBAL_CONTROL_IP: tor
      GLOBAL_CONTROL_PORT: 9051
      GLOBAL_ENABLE_VANGUARDS: "True"
      GLOBAL_ENABLE_BANDGUARDS: "True"
      GLOBAL_ENABLE_CBTVERIFY: "False"
      GLOBAL_ENABLE_RENDGUARD: "True"
      GLOBAL_CLOSE_CIRCUITS: "True"
      GLOBAL_ONE_SHOT_VANGUARDS: "False"
      GLOBAL_LOGLEVEL: NOTICE
      VANGUARDS_LAYER1_LIFETIME_DAYS: 0
      VANGUARDS_MAX_LAYER2_LIFETIME_HOURS: 1080
      VANGUARDS_MAX_LAYER3_LIFETIME_HOURS: 48
      VANGUARDS_MIN_LAYER2_LIFETIME_HOURS: 24
      VANGUARDS_MIN_LAYER3_LIFETIME_HOURS: 1
      VANGUARDS_NUM_LAYER1_GUARDS: 2
      VANGUARDS_NUM_LAYER2_GUARDS: 3
      VANGUARDS_NUM_LAYER3_GUARDS: 8
      BANGUARDS_CIRC_MAX_AGE_HOURS: 24
      BANGUARDS_CIRC_MAX_HSDESC_KILOBYTES: 30
      BANGUARDS_CIRC_MAX_MEGABYTES: 0
      BANGUARDS_CIRC_MAX_DISCONNECTED_SECS: 30
      BANGUARDS_CONN_MAX_DISCONNECTED_SECS: 15
      RENDGUARD_REND_USE_MAX_USE_TO_BW_RATIO: 5.0
      RENDGUARD_REND_USE_MAX_CONSENSUS_WEIGHT_CHURN: 1.0
      RENDGUARD_REND_USE_CLOSE_CIRCUITS_ON_OVERUSE: "True"
      RENDGUARD_REND_USE_GLOBAL_START_COUNT: 1000
      RENDGUARD_REND_USE_RELAY_START_COUNT: 100
      RENDGUARD_REND_USE_SCALE_AT_COUNT: 20000
    volumes:
      - tor_volume:/var/lib/tor/hidden_service/
    depends_on:
      - tor

  httpd:
    image: nginx:stable-alpine
    restart: always
    environment:
      NGINX_HOST: 0.0.0.0
      NGINX_PORT: 8080

volumes:
  tor_volume:
